config/routes.rb
Rails.application.routes.draw do
  get 'finders/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :serviceareas, :vehicles, :finders
  devise_for :users, path: 'users',  controllers: {
    sessions: 'users/sessions'
  }

  devise_for :lcvowners, path: 'lcvowners',  controllers: {
    sessions: 'lcvowners/sessions'
  }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<% if current_user %>
  <%= link_to 'Logout-user' ,destroy_user_session_path, method: :delete%>
  <%= link_to 'edit-user' ,edit_user_registration_path%>
  <%= link_to 'list lcvowners' ,finders_index_path%>

<% elsif current_lcvowner %>
  <%= link_to 'Logout-lcvowner' ,destroy_lcvowner_session_path, method: :delete%>
  <%= link_to 'edit-lcvowner' ,edit_lcvowner_registration_path%>
  <%= link_to 'listVehicles-lcvowner' ,vehicles_path%>

<% else %>
  <%= link_to 'HOME' ,root_path, class: "btn btn-primary"%>
  <%= link_to 'Login  - lcvowner' ,new_lcvowner_session_path, class:"btn btn-primary"%>
  <%= link_to 'Signup - lcvowner' ,new_lcvowner_registration_path, class:"btn btn-primary"%>
  <%= link_to 'Login  - user' ,new_user_session_path, class:"btn btn-success" %>
  <%= link_to 'Signup - user' ,new_user_registration_path, class: "btn btn-secondary"%>
<% end %>