config/routes.rb
Rails.application.routes.draw do
  get 'finders/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :serviceareas, :vehicles, :finders
  devise_for :users, path: 'users',  controllers: {
    sessions: 'users/sessions'
  }

  devise_for :lcvowners, path: 'lcvowners',  controllers: {
    sessions: 'lcvowners/sessions'
  }

end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :lcvowner
  has_many :serviceareas
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    if current_lcvowner
      @vehicles = current_lcvowner.vehicles
    end
  end

  def new
    @vehicle = current_lcvowner.vehicles.new
  end

  def create
    # @vehicle = current_lcvowner.vehicles.new(params[:vehicle])
    if current_lcvowner.vehicles.create(vehicle_params)
      redirect_to vehicles_path, notice: "Vehicle added successfully"
    else
      redirect_to vehicles_path, alert: "Error while inserting vehicle"
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update(vehicle_params)
      redirect_to vehicles_path, notice: "Vehicle added successfully"
    else
      redirect_to vehicles_path, alert: "Error while inserting vehicle"
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @lcvowner = @vehicle.lcvowner
    @serviceareas = @vehicle.serviceareas
    @isOwner = false
  
    if current_user
      @isOwner = false;
    elsif current_lcvowner
      @isOwner = true;
    end

  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.destroy
      redirect_to vehicles_path, notice: "Vehicle deleted successfully"
    else
      redirect_to vehicles_path, alert: "Error while deleting vehicle"
    end
  end

  private
  def vehicle_params
    params.require(:vehicle).permit(:name,:brand,:model,:capacity,:permit_type,:body_type);
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/create.html.erb
<h1>Vehicles#create</h1>
<p>Find me in app/views/vehicles/create.html.erb</p>

app/views/vehicles/destroy.html.erb
<h1>Vehicles#destroy</h1>
<p>Find me in app/views/vehicles/destroy.html.erb</p>

app/views/vehicles/edit.html.erb
<h1>Vehicles#edit</h1>
<p>Find me in app/views/vehicles/edit.html.erb</p>

<h1>Edit vehicle</h1>

<%= render 'layouts/vehicle' %>


<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Vehicles#index</h1>
<p>Find me in app/views/vehicles/index.html.erb</p>

<h1>Listing vehicles for LCV owner</h1>
 
 
<table>
  <tr>
    <th>name</th>
    <th>brand</th>
    <th>model</th>
    <th>capacity</th>
    <th>permit type</th>
    <th>body type</th>
  </tr>
 
<% @vehicles.each do |vehicle| %>
  <tr>
    <td><%= vehicle.name %></td>
    <td><%= vehicle.brand %></td>
    <td><%= vehicle.model %></td>
    <td><%= vehicle.capacity %></td>
    <td><%= vehicle.permit_type %></td>
    <td><%= vehicle.body_type %></td>
    <td><%= link_to 'Show', vehicle %></td>
    <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
    <td><%= link_to 'delete', vehicle, :confirm => 'Are you sure?',
                                     :method => :delete %></td>
  </tr>
<% end %>
</table>
 
<br />
 

<%= link_to 'New vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>Vehicles#new</h1>
<p>Find me in app/views/vehicles/new.html.erb</p>

<h1>New vehicle</h1>

<%= render 'layouts/vehicle' %>


<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<h1>Vehicles#update</h1>
<p>Find me in app/views/vehicles/update.html.erb</p>

<h1>show vehicle</h1>


<p id="notice"><%= notice %></p>
 
 <p>
  <b>LCV Owner:</b>
  <%= @lcvowner.email %>
</p>

<p>
  <b>Name:</b>
  <%= @vehicle.name %>
</p>
 
<p>
  <b>brand:</b>
  <%= @vehicle.brand %>
</p>
 
<p>
  <b>model:</b>
  <%= @vehicle.model %>
</p>
 
  
<p>
  <b>capacity:</b>
  <%= @vehicle.capacity %>
</p>
 
  
<p>
  <b>permit_type:</b>
  <%= @vehicle.permit_type %>
</p>
 
  
<p>
  <b>body_type:</b>
  <%= @vehicle.body_type %>
</p>

<h1>Listing service areas for this vehicle</h1>
 
 
<table>
  <tr>
    <th>name</th>
    <th>pincode</th>
  </tr>
 
<% @serviceareas.each do |servicearea| %>
  <tr>
    <td><%= servicearea.name %></td>
    <td><%= servicearea.pincode %></td>
    <% if @isOwner %>
      <td><%= link_to 'Edit', edit_servicearea_path(servicearea) %></td>
      <td><%= link_to 'delete', servicearea, :confirm => 'Are you sure?',
                                      :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>
 
<br />

 <% if @isOwner %>
  <%= link_to 'Add new service area', new_servicearea_path(vehicle_id: @vehicle.id) %> |
  <%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
  <%= link_to 'Back to listings', vehicles_path %> |
<% else %>
<%= link_to 'Back', :back %>
<% end %>